"""Added column abstract to post.Post

Revision ID: 3c53e1e9ff02
Revises: 3f48c9cb8868
Create Date: 2019-07-29 07:48:02.392824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c53e1e9ff02'
down_revision = '3f48c9cb8868'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('abstract', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'abstract')
    # ### end Alembic commands ###
