"""Added Post.read

Revision ID: 3f224c3a9e3a
Revises: 86490514cbcb
Create Date: 2019-08-11 20:55:33.773258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f224c3a9e3a'
down_revision = '86490514cbcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('read', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_posts_read'), 'posts', ['read'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_read'), table_name='posts')
    op.drop_column('posts', 'read')
    # ### end Alembic commands ###
