"""Added table admins

Revision ID: 544dd62e2e84
Revises: bdfc78d56748
Create Date: 2019-07-31 21:55:19.264433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '544dd62e2e84'
down_revision = 'bdfc78d56748'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('password', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admins_username'), 'admins', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admins_username'), table_name='admins')
    op.drop_table('admins')
    # ### end Alembic commands ###
