"""Added table posts

Revision ID: 59a90cfc11e4
Revises: e01a5502ee12
Create Date: 2019-07-25 23:40:37.675988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59a90cfc11e4'
down_revision = 'e01a5502ee12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=140), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('ctime', sa.DateTime(), nullable=True),
    sa.Column('mtime', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_ctime'), 'posts', ['ctime'], unique=False)
    op.create_index(op.f('ix_posts_mtime'), 'posts', ['mtime'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_mtime'), table_name='posts')
    op.drop_index(op.f('ix_posts_ctime'), table_name='posts')
    op.drop_table('posts')
    # ### end Alembic commands ###
