"""Added RelatedPost

Revision ID: 7e9955af75e5
Revises: 60cb15542187
Create Date: 2019-08-12 12:21:15.006161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e9955af75e5'
down_revision = '60cb15542187'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('related_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target', sa.Integer(), nullable=True),
    sa.Column('related', sa.Integer(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['related'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['target'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_related_posts_target'), 'related_posts', ['target'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_related_posts_target'), table_name='related_posts')
    op.drop_table('related_posts')
    # ### end Alembic commands ###
