"""Added column content_type to table posts

Revision ID: 86490514cbcb
Revises: 544dd62e2e84
Create Date: 2019-08-08 00:33:22.763647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86490514cbcb'
down_revision = '544dd62e2e84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('content_type', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'content_type')
    # ### end Alembic commands ###
