"""Altered tags.name

Revision ID: bdfc78d56748
Revises: a56c2f03ec10
Create Date: 2019-07-30 22:02:16.938468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdfc78d56748'
down_revision = 'a56c2f03ec10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    # ### end Alembic commands ###
