"""Replaced Post.abstract with content_text

Revision ID: d55998d2561d
Revises: 7e9955af75e5
Create Date: 2019-08-13 03:02:53.322311

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd55998d2561d'
down_revision = '7e9955af75e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('content_text', sa.Text(), nullable=True))
    op.drop_column('posts', 'abstract')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('abstract', mysql.VARCHAR(length=100), nullable=True))
    op.drop_column('posts', 'content_text')
    # ### end Alembic commands ###
