"""Added foreign keys to mails

Revision ID: df0a7a5cfe1f
Revises: ce9aea8df325
Create Date: 2019-07-27 00:15:02.204417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df0a7a5cfe1f'
down_revision = 'ce9aea8df325'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mails', sa.Column('receiver_id', sa.Integer(), nullable=True))
    op.add_column('mails', sa.Column('sender_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'mails', 'users', ['receiver_id'], ['id'])
    op.create_foreign_key(None, 'mails', 'users', ['sender_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mails', type_='foreignkey')
    op.drop_constraint(None, 'mails', type_='foreignkey')
    op.drop_column('mails', 'sender_id')
    op.drop_column('mails', 'receiver_id')
    # ### end Alembic commands ###
